/*
 * This file is generated by jOOQ.
*/
package db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUser extends Serializable {

    /**
     * Setter for <code>PUBLIC.USER.ID</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>PUBLIC.USER.ID</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>PUBLIC.USER.NAME</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>PUBLIC.USER.NAME</code>.
     */
    public String getName();

    /**
     * Setter for <code>PUBLIC.USER.ADDRESS</code>.
     */
    public void setAddress(String value);

    /**
     * Getter for <code>PUBLIC.USER.ADDRESS</code>.
     */
    public String getAddress();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser
     */
    public void from(db.tables.interfaces.IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser
     */
    public <E extends db.tables.interfaces.IUser> E into(E into);
}
